project_id = "syldobdcdsgfgjtbuwxm"

[functions.get-secret]
verify_jwt = true

[functions.secure-flex-api]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.place-photos]
verify_jwt = false

[functions.place-restaurants]
verify_jwt = false

[functions.staffing-click]
verify_jwt = false

[functions.push]
verify_jwt = true

[functions.send-job-payout-email]
verify_jwt = true

[functions.send-timesheet-reminder]
verify_jwt = true

[functions.auto-send-timesheet-reminders]
verify_jwt = false
