project_id = "syldobdcdsgfgjtbuwxm"

[db]
port = 54322
major_version = 15

[functions.get-secret]
verify_jwt = true

[functions.secure-flex-api]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.place-photos]
verify_jwt = false

[functions.place-restaurants]
verify_jwt = false

[functions.staffing-click]
verify_jwt = false

[functions.staffing-orchestrator]
verify_jwt = false

[functions.staffing-sweeper]
verify_jwt = false

[functions.push]
verify_jwt = true

[functions.send-job-payout-email]
verify_jwt = true

[functions.send-timesheet-reminder]
verify_jwt = true

[functions.auto-send-timesheet-reminders]
verify_jwt = false

[functions.cleanup-corporate-email-images]
verify_jwt = false

[functions.wallboard-feed]
verify_jwt = true

[functions.tech-calendar-ics]
verify_jwt = false

[functions.upload-public-artist-rider]
verify_jwt = false

[functions.delete-public-artist-rider]
verify_jwt = false

[functions.submit-public-artist-form]
verify_jwt = false
